service: gen-service
provider:
  name: aws
  runtime: go1.x

stage: dev
region: eu-west-1

package:
 exclude:
   - ./**
 include:
   - ./bin/**

functions:
  name-generator:
    handler: bin/name-generator
    events:
    - http:
        path: generate
        method: post